apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods

subjects:
- kind: ServiceAccount
  name: benny-svc-acc 
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: resource-reader
  apiGroup: rbac.authorization.k8s.io
