apiVersion: apps/v1
kind: Deployment
metadata:
  name: benny-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benny-app
  template:
    metadata:
      labels:
        app: benny-app
    spec:
      serviceAccountName: benny-svc-acc
      containers:
        - name: benny-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullpolicy}}"
          ports:
            - containerPort: 8501
