{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: benny-app

spec:
  ingressClassName: {{ .Values.ingress.type }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: benny-app
                port:
                  number: {{ .Values.service.port }}
{{- end }}
